"""生成 12 个 Skill Manifest."""

from pathlib import Path

import yaml

SKILLS = [
    {
        "id": "intent-classify",
        "version": "1.0.0",
        "name": "意图识别",
        "description": "识别用户意图类别，不生成回复",
        "agent": "router-agent",
        "boundary": {
            "does": ["识别咨询/工单/投诉/退款/闲聊"],
            "does_not": ["生成回复", "调用 Tool", "创建工单"],
        },
        "inputs": ["conversation_context"],
        "outputs": ["intent", "confidence"],
        "tools": [],
        "memory_deps": ["working"],
        "prompt_template": "skills/prompts/intent-classify.md",
        "eval_suite": "evaluation/skills/intent-classify/",
        "fallback": "rule-engine.clarify-intent",
    },
    {
        "id": "agent-route",
        "version": "1.0.0",
        "name": "Agent 路由",
        "description": "根据意图路由到专业 Agent",
        "agent": "router-agent",
        "boundary": {"does": ["选择目标 Agent"], "does_not": ["执行业务 Skill"]},
        "inputs": ["intent"],
        "outputs": ["target_agent"],
        "tools": [],
        "memory_deps": ["working"],
        "prompt_template": "skills/prompts/agent-route.md",
        "eval_suite": "evaluation/skills/agent-route/",
        "fallback": "rule-engine.default-consult",
    },
    {
        "id": "knowledge-retrieve",
        "version": "1.0.0",
        "name": "知识检索",
        "description": "RAG 检索，不生成用户可见回复",
        "agent": "consult-agent",
        "boundary": {"does": ["向量检索", "返回 source_refs"], "does_not": ["生成最终回复", "建单"]},
        "inputs": ["conversation_context"],
        "outputs": ["chunks", "source_refs"],
        "tools": ["vector_search.query"],
        "memory_deps": ["working", "semantic"],
        "prompt_template": "skills/prompts/knowledge-retrieve.md",
        "eval_suite": "evaluation/skills/knowledge-retrieve/",
        "fallback": "rule-engine.no-knowledge",
    },
    {
        "id": "answer-compose",
        "version": "1.0.0",
        "name": "回答生成",
        "description": "基于检索结果生成用户回复",
        "agent": "consult-agent",
        "boundary": {"does": ["生成带引用的回复"], "does_not": ["检索", "建单"]},
        "inputs": ["chunks", "source_refs"],
        "outputs": ["response"],
        "tools": [],
        "memory_deps": ["working"],
        "prompt_template": "skills/prompts/answer-compose.md",
        "eval_suite": "evaluation/skills/answer-compose/",
        "fallback": "rule-engine.template-answer",
    },
    {
        "id": "ticket-create",
        "version": "1.0.0",
        "name": "工单创建",
        "description": "提取字段并创建工单",
        "agent": "ticket-agent",
        "boundary": {
            "does": ["提取字段", "校验", "调用创建 API"],
            "does_not": ["查询工单", "修改工单", "关闭工单"],
        },
        "inputs": ["conversation_context", "user_profile"],
        "outputs": ["ticket_id", "ticket_summary"],
        "tools": ["ticket_api.create", "crm_api.get_customer"],
        "memory_deps": ["working", "profile"],
        "prompt_template": "skills/prompts/ticket-create.md",
        "eval_suite": "evaluation/skills/ticket-create/",
        "fallback": "rule-engine.ticket-template",
    },
    {
        "id": "ticket-query",
        "version": "1.0.0",
        "name": "工单查询",
        "description": "查询工单进度",
        "agent": "ticket-agent",
        "boundary": {"does": ["查询工单状态"], "does_not": ["创建工单", "修改工单"]},
        "inputs": ["conversation_context"],
        "outputs": ["ticket_status"],
        "tools": ["ticket_api.get"],
        "memory_deps": ["working", "episodic"],
        "prompt_template": "skills/prompts/ticket-query.md",
        "eval_suite": "evaluation/skills/ticket-query/",
        "fallback": "rule-engine.ask-ticket-id",
    },
    {
        "id": "ticket-update",
        "version": "1.0.0",
        "name": "工单更新",
        "description": "更新工单字段或状态（经规则引擎）",
        "agent": "ticket-agent",
        "boundary": {"does": ["提取更新意图"], "does_not": ["创建工单"]},
        "inputs": ["conversation_context", "ticket_id"],
        "outputs": ["update_result"],
        "tools": ["ticket_api.update"],
        "memory_deps": ["working"],
        "prompt_template": "skills/prompts/ticket-update.md",
        "eval_suite": "evaluation/skills/ticket-update/",
        "fallback": "rule-engine.update-denied",
    },
    {
        "id": "escalation-judge",
        "version": "1.0.0",
        "name": "升级判断",
        "description": "判断是否需要升级，不直接转人工",
        "agent": "escalation-agent",
        "boundary": {"does": ["升级条件判断"], "does_not": ["执行转人工"]},
        "inputs": ["conversation_context", "sentiment_score"],
        "outputs": ["need_escalation", "reason"],
        "tools": [],
        "memory_deps": ["working", "episodic"],
        "prompt_template": "skills/prompts/escalation-judge.md",
        "eval_suite": "evaluation/skills/escalation-judge/",
        "fallback": "rule-engine.escalate-threshold",
    },
    {
        "id": "human-handoff",
        "version": "1.0.0",
        "name": "转人工",
        "description": "执行转人工（规则引擎）",
        "agent": "escalation-agent",
        "boundary": {"does": ["写入升级队列"], "does_not": ["业务处理", "LLM 回复"]},
        "inputs": ["ticket_id", "reason"],
        "outputs": ["queue_id"],
        "tools": ["human_handoff.execute"],
        "memory_deps": ["working", "profile"],
        "prompt_template": "skills/prompts/human-handoff.md",
        "eval_suite": "evaluation/skills/human-handoff/",
        "fallback": "rule-engine.handoff-fallback",
    },
    {
        "id": "sentiment-analyze",
        "version": "1.0.0",
        "name": "情绪分析",
        "description": "分析用户情绪，不决定升级策略",
        "agent": "escalation-agent",
        "boundary": {"does": ["输出情绪分数"], "does_not": ["决定升级", "转人工"]},
        "inputs": ["conversation_context"],
        "outputs": ["sentiment_score", "sentiment_label"],
        "tools": [],
        "memory_deps": ["working"],
        "prompt_template": "skills/prompts/sentiment-analyze.md",
        "eval_suite": "evaluation/skills/sentiment-analyze/",
        "fallback": "rule-engine.neutral-sentiment",
    },
    {
        "id": "crm-lookup",
        "version": "1.0.0",
        "name": "CRM 查询",
        "description": "只读查询客户信息",
        "agent": "shared",
        "boundary": {"does": ["查询 CRM"], "does_not": ["修改 CRM 数据"]},
        "inputs": ["customer_id"],
        "outputs": ["customer_profile"],
        "tools": ["crm_api.get_customer"],
        "memory_deps": ["profile"],
        "prompt_template": "skills/prompts/crm-lookup.md",
        "eval_suite": "evaluation/skills/crm-lookup/",
        "fallback": "rule-engine.customer-not-found",
    },
    {
        "id": "compliance-check",
        "version": "1.0.0",
        "name": "合规检查",
        "description": "合规前置拦截",
        "agent": "harness",
        "boundary": {"does": ["合规规则匹配"], "does_not": ["业务回复"]},
        "inputs": ["message"],
        "outputs": ["allowed", "reason"],
        "tools": [],
        "memory_deps": [],
        "prompt_template": "skills/prompts/compliance-check.md",
        "eval_suite": "evaluation/skills/compliance-check/",
        "fallback": "rule-engine.compliance-block",
    },
]


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "skills" / "manifests"
    for skill in SKILLS:
        path = out / f"{skill['id']}.yaml"
        path.write_text(
            yaml.dump(skill, allow_unicode=True, sort_keys=False),
            encoding="utf-8",
        )
    print(f"Generated {len(SKILLS)} manifests in {out}")


if __name__ == "__main__":
    main()
